# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_libs.face_pb2 as face__pb2


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_emotion = channel.unary_unary(
                '/AIService/check_emotion',
                request_serializer=face__pb2.Request.SerializeToString,
                response_deserializer=face__pb2.Response.FromString,
                )
        self.detection_face = channel.unary_unary(
                '/AIService/detection_face',
                request_serializer=face__pb2.Request.SerializeToString,
                response_deserializer=face__pb2.Response.FromString,
                )


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_emotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def detection_face(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_emotion': grpc.unary_unary_rpc_method_handler(
                    servicer.check_emotion,
                    request_deserializer=face__pb2.Request.FromString,
                    response_serializer=face__pb2.Response.SerializeToString,
            ),
            'detection_face': grpc.unary_unary_rpc_method_handler(
                    servicer.detection_face,
                    request_deserializer=face__pb2.Request.FromString,
                    response_serializer=face__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_emotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIService/check_emotion',
            face__pb2.Request.SerializeToString,
            face__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def detection_face(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIService/detection_face',
            face__pb2.Request.SerializeToString,
            face__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
